### ISSUE TITLE
About me on the edge

### ISSUE THREAD

**Issue by Absumm** [Comfy-Themes/Discord#59] opened 2022-04-07 17:21 UTC
![image](https://user-images.githubusercontent.com/56665292/162260872-e1af5455-df3c-478e-8d81-4ec1e2ce110f.png)
About me is kinda broken and off to the very edge for some reason

**Comment by Danix421** [comment] 2022-04-09 02:50
![imagen](https://user-images.githubusercontent.com/78866931/162553740-ac2374c3-a3bf-437b-9229-f8b6e351e53a.png)
same here, teammates who use the theme report the same

**Comment by kusogakinerd** [comment] 2022-04-13 07:13
![image](https://user-images.githubusercontent.com/103561040/163120447-09ab9959-24fd-4434-b09f-089207f3b63b.png)
the about me for me still is on the edge, is it maybe the plugins that i have?

**Comment by Juknum** [comment] 2022-04-27 18:15
Same issue here
![image](https://user-images.githubusercontent.com/49886317/165592576-597b0859-9f48-4568-853b-54dec1867a31.png)

**Comment by kusogakinerd** [comment] 2022-04-28 12:50
> Same issue here ![image](https://user-images.githubusercontent.com/49886317/165592576-597b0859-9f48-4568-853b-54dec1867a31.png)

https://github.com/NYRI4/Comfy/pull/60/commits/0e94243520e3c88c41d64db2439c462f6041ad7d 
i figured it out
u just had to add this code inside the plugin

i had no idea that it was supposed to be added manually

**Comment by Juknum** [comment] 2022-04-28 22:09
Nice, it might also be related to the same bug for the "Add button" on bots :
![image](https://user-images.githubusercontent.com/49886317/165855968-0cf7eb46-3449-4d69-9afa-d904996cec1a.png)

**Comment by Juknum** [comment] 2022-05-24 23:49
I can't reproduce the issue anymore, it may have been fixed by itself @NYRI4

**Closed** 2022-05-25 10:31 UTC
